name: ServerLinksZ
version: '${project.version}'
main: com.zetaplugins.serverlinksz.ServerLinksZ
api-version: '1.21'
authors: [ Kartoffelchipss ]
description: A simple plugin to add Links to your server
website: strassburger.org

commands:
  serverlinksz:
    description: Main command for ServerLinksZ
    aliases:
      - sl
      - slz
      - serverlinks
  slzdebug:
    description: Debug command for ServerLinksZ
    permission: serverlinksz.admin
  link:
    description: Get a link

permissions:
  serverlinksz.admin:
    default: op
    description: Allows the user to manage the plugin